env = Environment()

env['APP_TARGET'] = 'LastSupperApp'
env['APP_SOURCES'] = ['LastSupperApp.cpp', 'Capture1394PParams.cpp', 'CaptureSource.cpp',
				'KawaseStreak.cpp']
env['APP_SOURCES'] += ['FluidParticlesEffect.cpp', 'FluidParticles.cpp']
env['DEBUG'] = 0

SConscript('../blocks/msaFluid/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')
SConscript('../../../../blocks/Cinder-Capture1394/scons/SConscript', exports = 'env')
SConscript('../../../../scons/SConscript', exports = 'env')

